apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zgjk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zgjk
    app.kubernetes.io/part-of: tkrw-pr714-0075-0049-app
  name: devfile-sample-zgjk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zgjk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zgjk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0049-tenant/tkrw-pr714-0075-0049-app/devfile-sample-zgjk@sha256:a6f2fd2e90191620c4d6b92f4b1b11b279db1b8b612681d9a24e0cf96944633e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
